### ISSUE TITLE
Error during self update

### ISSUE THREAD

**Issue by chriha** [chriha/project-cli#1]
`self-update` throws exception, but still succeeds:
```
PHP Warning:  include(phar:///usr/local/bin/project/vendor/composer/../symfony/yaml/Dumper.php): failed to open stream: phar error: internal corruption of phar "/usr/local/bin/project" (actual filesize mismatch on file "vendor/symfony/yaml/Dumper.php") in phar:///usr/local/bin/project/.box/vendor/composer/ClassLoader.php on line 444

Warning: include(phar:///usr/local/bin/project/vendor/composer/../symfony/yaml/Dumper.php): failed to open stream: phar error: internal corruption of phar "/usr/local/bin/project" (actual filesize mismatch on file "vendor/symfony/yaml/Dumper.php") in phar:///usr/local/bin/project/.box/vendor/composer/ClassLoader.php on line 444
PHP Warning:  include(): Failed opening 'phar:///usr/local/bin/project/vendor/composer/../symfony/yaml/Dumper.php' for inclusion (include_path='.:/usr/local/Cellar/php@7.2/7.2.22_1/share/php@7.2/pear') in phar:///usr/local/bin/project/.box/vendor/composer/ClassLoader.php on line 444

Warning: include(): Failed opening 'phar:///usr/local/bin/project/vendor/composer/../symfony/yaml/Dumper.php' for inclusion (include_path='.:/usr/local/Cellar/php@7.2/7.2.22_1/share/php@7.2/pear') in phar:///usr/local/bin/project/.box/vendor/composer/ClassLoader.php on line 444
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Yaml\Dumper' not found in phar:///usr/local/bin/project/vendor/symfony/yaml/Yaml.php:97
Stack trace:
#0 phar:///usr/local/bin/project/src/Libraries/Config/Application.php(102): Symfony\Component\Yaml\Yaml::dump(Array)
#1 phar:///usr/local/bin/project/src/Libraries/Config/Application.php(89): Chriha\ProjectCLI\Libraries\Config\Application->save()
#2 [internal function]: Chriha\ProjectCLI\Libraries\Config\Application->__destruct()
#3 {main}
  thrown in phar:///usr/local/bin/project/vendor/symfony/yaml/Yaml.php on line 97

Fatal error: Uncaught Error: Class 'Symfony\Component\Yaml\Dumper' not found in phar:///usr/local/bin/project/vendor/symfony/yaml/Yaml.php:97
Stack trace:
#0 phar:///usr/local/bin/project/src/Libraries/Config/Application.php(102): Symfony\Component\Yaml\Yaml::dump(Array)
#1 phar:///usr/local/bin/project/src/Libraries/Config/Application.php(89): Chriha\ProjectCLI\Libraries\Config\Application->save()
#2 [internal function]: Chriha\ProjectCLI\Libraries\Config\Application->__destruct()
#3 {main}
  thrown in phar:///usr/local/bin/project/vendor/symfony/yaml/Yaml.php on line 97
```

**Comment by chriha** [comment]
Solved in previous version
